import { Map } from 'lucide-react';
import { intelligenceApi } from '../../../api/intelligence.api';
import { useIntelligenceQuery } from '../useIntelligenceQuery';
export default function HeatMap() {
  const { data, loading, error, retry } = useIntelligenceQuery(() => intelligenceApi.getHeatMap({}), []);
  const points = Array.isArray(data?.points) ? data.points : [];
  if (loading) return <div className="rounded-2xl border border-white/10 bg-navy-800/50 p-10 text-center text-ink/60">Loading recorded property coordinates…</div>;
  if (error) return <div className="rounded-2xl border border-rose-400/30 bg-navy-800/50 p-10 text-center text-ink/60">{error}<button onClick={retry} className="mx-auto mt-4 block text-gold-400">Retry</button></div>;
  if (!points.length) return <div className="rounded-2xl border border-white/10 bg-navy-800/50 p-10 text-center text-ink/60">{data?.message || 'No valid property coordinates are available.'}<button onClick={retry} className="mx-auto mt-4 block text-gold-400">Retry</button></div>;
  return <div className="max-w-6xl space-y-6"><div><h2 className="flex items-center gap-2 font-heading text-2xl font-bold text-cream"><Map className="h-6 w-6 text-gold-400" />Property Coordinate Coverage</h2><p className="text-sm text-ink/60">Returned property coordinates are listed below. A geographic heat layer is unavailable because the verified API does not provide heat intensities.</p></div><section className="overflow-hidden rounded-2xl border border-white/10 bg-navy-800/50"><div className="max-h-[560px] overflow-auto"><table className="min-w-full text-left text-sm"><thead className="sticky top-0 border-b border-white/10 bg-navy-800 text-xs uppercase text-ink/60"><tr><th className="p-4">Property</th><th className="p-4">Location</th><th className="p-4">Latitude</th><th className="p-4">Longitude</th></tr></thead><tbody>{points.map((point: any, index: number) => <tr className="border-b border-white/5" key={point._id || point.id || index}><td className="p-4 text-cream">{point.title || point.name || point._id || 'Property record'}</td><td className="p-4 text-ink/70">{point.location || point.address || 'Not supplied'}</td><td className="p-4 text-ink/70">{point.latitude ?? point.lat ?? '—'}</td><td className="p-4 text-ink/70">{point.longitude ?? point.lng ?? '—'}</td></tr>)}</tbody></table></div></section></div>;
}
