export const ROLES = {
  BUYER: 'Buyer',
  OWNER: 'Owner',
  AGENT: 'Agent',
  AGENCY: 'Agency',
  ADMIN: 'Admin',
  SUPER_ADMIN: 'Super Admin',
  MANAGER: 'Manager',
  PROCUREMENT: 'Procurement Officer',
  FINANCE: 'Finance Manager',
  ANALYST: 'Data Analyst',
  PROPERTY_MANAGER: 'Property Manager',
  SERVICE_ADMIN: 'Service Manager',
} as const;

export const MANAGEMENT_ALLOWED_ROLES = [ROLES.ADMIN, ROLES.SUPER_ADMIN, ROLES.MANAGER];
export const PROCUREMENT_ALLOWED_ROLES = [ROLES.ADMIN, ROLES.SUPER_ADMIN, ROLES.PROCUREMENT];
export const FINANCE_ALLOWED_ROLES = [ROLES.ADMIN, ROLES.SUPER_ADMIN, ROLES.FINANCE];
export const INTELLIGENCE_ALLOWED_ROLES = [ROLES.ADMIN, ROLES.SUPER_ADMIN, ROLES.ANALYST];
export const PROPERTY_MANAGEMENT_ALLOWED_ROLES = [ROLES.ADMIN, ROLES.SUPER_ADMIN, ROLES.PROPERTY_MANAGER];
export const HOME_SERVICES_ALLOWED_ROLES = [ROLES.ADMIN, ROLES.SUPER_ADMIN, ROLES.SERVICE_ADMIN];

export const ALL_ENTERPRISE_ALLOWED_ROLES = [
  ROLES.ADMIN, 
  ROLES.SUPER_ADMIN, 
  ROLES.MANAGER, 
  ROLES.AGENT, 
  ROLES.AGENCY,
  ROLES.FINANCE, 
  ROLES.PROCUREMENT, 
  ROLES.ANALYST, 
  ROLES.PROPERTY_MANAGER, 
  ROLES.SERVICE_ADMIN
];

