export const ROUTES = {
  HOME: '/',
  PROPERTIES: '/properties',
  PROPERTY_DETAILS: '/properties/:id',
  AGENCIES: '/agencies',
  AGENCY_DETAILS: '/agencies/:slug',
  AGENT_DETAILS: '/agents/:slug',
  SEARCH: '/search',
  ABOUT: '/about',
  COMMUNICATION: '/communication',
  NOTIFICATIONS: '/notifications',
  WORKFLOW_CENTER: '/workflow-center',
  DOCUMENT_CENTER: '/document-center',
  CRM_CENTER: '/crm-center',
  FINANCE_CENTER: '/finance-center',
  COMPLIANCE_CENTER: '/compliance-center',
  HR_CENTER: '/hr-center',

  // Error Pages
  UNAUTHORIZED: '/unauthorized',
  TERMS: '/terms',
  CONTACT: '/contact',
  FAQ: '/faq',
  PRIVACY: '/privacy',
  LOGIN: '/login',
  REGISTER: '/register',
  BUYER_DASHBOARD: '/buyer-dashboard',
  OWNER_DASHBOARD: '/owner-dashboard',
  AGENT_DASHBOARD: '/agent-dashboard',
  AGENCY_DASHBOARD: '/agency-dashboard',
  ADMIN_DASHBOARD: '/dashboard',
  SUPER_ADMIN_DASHBOARD: '/admin-dashboard',
  MANAGEMENT_DASHBOARD: '/management-dashboard',
  PROCUREMENT_DASHBOARD: '/procurement-dashboard',
  FINANCE_DASHBOARD: '/finance-dashboard',
  INTELLIGENCE_DASHBOARD: '/intelligence-dashboard',
  PROPERTY_MANAGEMENT_DASHBOARD: '/property-management-dashboard',
  HOME_SERVICES_DASHBOARD: '/home-services-dashboard',
  COMMUNICATION_CENTER: '/communication-center',
  NOTIFICATION_CENTER: '/notification-center',
} as const;
