export const ROUTES = {
  HOME: '/',
  PROPERTIES: '/properties',
  PROPERTY_DETAILS: '/properties/:id',
  SEARCH: '/search',
  ABOUT: '/about',
  CONTACT: '/contact',
  FAQ: '/faq',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  LOGIN: '/login',
  REGISTER: '/register',
  BUYER_DASHBOARD: '/buyer-dashboard',
  OWNER_DASHBOARD: '/owner-dashboard',
  AGENT_DASHBOARD: '/agent-dashboard',
  AGENCY_DASHBOARD: '/agency-dashboard',
  ADMIN_DASHBOARD: '/dashboard',
  SUPER_ADMIN_DASHBOARD: '/admin-dashboard',
  MANAGEMENT_DASHBOARD: '/management-dashboard',
  PROCUREMENT_DASHBOARD: '/procurement-dashboard',
  FINANCE_DASHBOARD: '/finance-dashboard',
  INTELLIGENCE_DASHBOARD: '/intelligence-dashboard',
  PROPERTY_MANAGEMENT_DASHBOARD: '/property-management-dashboard',
  HOME_SERVICES_DASHBOARD: '/home-services-dashboard',
} as const;
