import { useEffect, useState } from 'react';
import { Modal } from '../../../../components/ui/Modal';
import { GoldButton } from '../../../../components/ui/ui';
import { Input } from '../../../../components/ui/Input';
import { Select } from '../../../../components/ui/Select';
interface Props { isOpen: boolean; onClose: () => void; onSubmit: (values: any) => Promise<void>; initialData?: any; properties: any[]; submitting?: boolean; error?: string | null }
export function TenantFormModal({ isOpen, onClose, onSubmit, initialData, properties, submitting, error }: Props) {
  const [values, setValues] = useState<any>({ fullName: '', email: '', phone: '', unit: '', status: 'Active', propertyId: '' });
  useEffect(() => { setValues({ fullName: initialData?.fullName || '', email: initialData?.email || '', phone: initialData?.phone || '', unit: initialData?.unit || '', status: initialData?.status || 'Active', propertyId: initialData?.property?._id || initialData?.property || properties[0]?._id || '' }); }, [initialData, isOpen, properties]);
  return <Modal isOpen={isOpen} onClose={onClose} title={initialData?._id ? 'Edit Tenant' : 'Add New Tenant'} size="lg" actionButton={<GoldButton onClick={() => void onSubmit(values)} disabled={submitting || !values.fullName || !values.propertyId}>{submitting ? 'Saving…' : initialData?._id ? 'Save Changes' : 'Add Tenant'}</GoldButton>}><div className="grid gap-5 md:grid-cols-2">{error && <p className="md:col-span-2 text-sm text-rose-300">{error}</p>}<Input label="Full Name" value={values.fullName} onChange={e => setValues({ ...values, fullName: e.target.value })} /><Input label="Email Address" type="email" value={values.email} onChange={e => setValues({ ...values, email: e.target.value })} /><Input label="Phone Number" value={values.phone} onChange={e => setValues({ ...values, phone: e.target.value })} /><Input label="Unit" value={values.unit} onChange={e => setValues({ ...values, unit: e.target.value })} /><Select label="Property" value={values.propertyId} disabled={Boolean(initialData?._id)} options={properties.map(p => ({ value: p._id, label: p.title }))} onChange={e => setValues({ ...values, propertyId: e.target.value })} /><Select label="Status" value={values.status} options={['Active', 'Moving Out', 'Past', 'Eviction'].map(value => ({ value, label: value }))} onChange={e => setValues({ ...values, status: e.target.value })} /></div></Modal>;
}
