import { useCallback, useEffect, useState } from 'react';
import { AlertCircle, RefreshCw } from 'lucide-react';
import { financeApi } from '../../../api/finance.api';
import { DataTable } from '../../../components/dashboard/shared/tables/DataTable';
import { DataTableToolbar } from '../../../components/dashboard/shared/filters/DataTableToolbar';
import { EmptyState } from '../../../components/layout/EmptyState';
import { GhostButton } from '../../../components/ui/ui';

const currency = (value: number, code = 'NGN') => new Intl.NumberFormat('en-NG', { style: 'currency', currency: code, maximumFractionDigits: 0 }).format(value || 0);
const config: Record<string, any> = {
  Revenue: { call: 'getRevenue', key: 'revenue', title: 'Revenue', empty: 'No completed Home Services revenue has been recorded.', columns: [['Reference', 'id'], ['Source', 'source'], ['Amount', 'amount'], ['Status', 'status'], ['Date', 'date']] },
  Transactions: { call: 'getTransactions', key: 'transactions', title: 'Transactions', empty: 'No payment or Home Services transactions are available.', columns: [['Reference', 'reference'], ['Type', 'type'], ['Description', 'description'], ['Amount', 'amount'], ['Status', 'status'], ['Date', 'date']] },
  'Owner Payments': { call: 'getOwnerPayments', key: 'payments', title: 'Owner Payments', empty: 'No owner payment records are available.', columns: [['Owner', 'owner'], ['Property', 'property'], ['Period', 'period'], ['Amount', 'amount'], ['Status', 'status'], ['Date', 'date']] },
  'Agency Earnings': { call: 'getAgencyEarnings', key: 'records', title: 'Agency Earnings', empty: 'No agency commission records are available.', columns: [['Reference', 'id'], ['Agency', 'recipient'], ['Property', 'property'], ['Amount', 'amount'], ['Status', 'status'], ['Due date', 'dueDate']] },
  'Agent Commissions': { call: 'getAgentCommissions', key: 'records', title: 'Agent Commissions', empty: 'No agent commission records are available.', columns: [['Reference', 'id'], ['Agent', 'recipient'], ['Property', 'property'], ['Amount', 'amount'], ['Status', 'status'], ['Due date', 'dueDate']] },
  'Mortgage Statistics': { call: 'getMortgageStatistics', key: 'applications', title: 'Mortgage Statistics', empty: 'No mortgage applications are available.', columns: [['Applicant', 'applicant'], ['Lender', 'lender'], ['Requested', 'requestedLoanAmount'], ['Approved', 'approvedLoanAmount'], ['Status', 'status'], ['Date', 'createdAt']] },
  Budget: { call: 'getProcurementBudget', key: 'budgets', title: 'Procurement Budget', empty: 'No procurement budget records are available.', columns: [['Reference', 'id'], ['Budget', 'name'], ['Department', 'department'], ['Amount', 'amount'], ['Status', 'status'], ['Date', 'createdAt']] },
  'Audit Logs': { call: 'getAuditLogs', key: 'logs', title: 'Finance Audit Logs', empty: 'No Finance-relevant audit events are available.', columns: [['Action', 'action'], ['Category', 'category'], ['Actor', 'actor'], ['Description', 'description'], ['Date', 'createdAt']] },
};
const display = (key: string, value: any, row: any) => key.toLowerCase().includes('amount') ? currency(value, row.currency) : value instanceof Date ? value.toLocaleDateString() : (typeof value === 'string' && /date|at$/i.test(key) ? new Date(value).toLocaleDateString() : value || '—');
export function FinanceDataView({ tab }: { tab: string }) { const item = config[tab]; const [data, setData] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const load = useCallback(async () => { setLoading(true); setError(''); try { const response: any = await (financeApi as any)[item.call](); setData(response?.data?.[item.key] || []); } catch (err: any) { setError(err?.message || 'Unable to load finance data.'); } finally { setLoading(false); } }, [item]); useEffect(() => { void load(); }, [load]); const rows = data.filter((row) => JSON.stringify(row).toLowerCase().includes(search.toLowerCase())); return <div className="space-y-6 max-w-7xl"><div className="flex items-center justify-between gap-4"><div><h2 className="font-heading text-2xl font-bold text-cream">{item.title}</h2><p className="text-sm text-ink/60">Live records from Luxora’s existing financial domains.</p></div><GhostButton onClick={() => void load()}><RefreshCw className="mr-2 h-4 w-4" />Refresh</GhostButton></div><DataTableToolbar searchValue={search} onSearchChange={setSearch} searchPlaceholder="Search records..." showRefresh onRefresh={() => void load()} />{error && <div className="flex gap-2 rounded-xl border border-rose-400/25 bg-rose-400/10 p-4 text-rose-200"><AlertCircle className="h-4 w-4" />{error}<button onClick={() => void load()} className="ml-auto underline">Retry</button></div>}<DataTable isLoading={loading} data={rows} keyExtractor={(row: any) => row.id} emptyState={<EmptyState title="No records yet" description={item.empty} />} columns={item.columns.map(([header, key]: string[]) => ({ header, render: (row: any) => display(key, row[key], row) }))} /></div>; }
export function FinanceOverview() { const [result, setResult] = useState<any>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const load = useCallback(async () => { setLoading(true); setError(''); try { setResult(await financeApi.getOverview()); } catch (err: any) { setError(err?.message || 'Unable to load finance overview.'); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]); const summary = result?.overview?.summary; return <div className="space-y-6 max-w-7xl"><div className="flex justify-between"><div><h2 className="font-heading text-2xl font-bold text-cream">Finance Overview</h2><p className="text-sm text-ink/60">Actual amounts are limited to their source domains.</p></div><GhostButton onClick={() => void load()}><RefreshCw className="mr-2 h-4 w-4" />Refresh</GhostButton></div>{error && <div className="rounded-xl border border-rose-400/25 bg-rose-400/10 p-4 text-rose-200">{error} <button className="underline" onClick={() => void load()}>Retry</button></div>}{loading ? <div className="py-20 text-center text-ink/50">Loading finance overview…</div> : <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[['Completed service revenue', summary?.realizedServiceRevenue], ['Owner payments collected', summary?.ownerPaymentsCollected], ['Pending owner payments', summary?.pendingOwnerPayments], ['Paid commission obligations', summary?.paidCommissionObligations], ['Pending commission obligations', summary?.pendingCommissionObligations], ['Active mortgage applications', summary?.activeMortgageApplications]].map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-white/10 bg-navy-800/50 p-5"><p className="text-xs uppercase text-ink/50">{label}</p><p className="mt-2 text-2xl font-bold text-gold-400">{String(label).includes('applications') ? value || 0 : currency(Number(value || 0))}</p></div>)}</div><DataTable data={result?.overview?.recentActivity || []} keyExtractor={(row: any) => row.id} emptyState={<EmptyState title="No Finance activity" description="Finance-relevant audit activity will appear here." />} columns={[{ header: 'Action', render: (row: any) => row.action }, { header: 'Category', render: (row: any) => row.category }, { header: 'Description', render: (row: any) => row.description }]} /></>}</div>; }
export function FinanceReports() { const [report, setReport] = useState<any>(null); const [error, setError] = useState(''); useEffect(() => { financeApi.getReports().then(setReport).catch((err: any) => setError(err.message)); }, []); return <div className="space-y-6 max-w-5xl"><h2 className="font-heading text-2xl font-bold text-cream">Finance Reports</h2>{error ? <p className="text-rose-300">{error}</p> : !report ? <p className="text-ink/50">Loading report…</p> : <div className="rounded-2xl border border-white/10 bg-navy-800/50 p-6"><p className="text-ink/60">{report?.reports?.report?.note}</p><pre className="mt-4 overflow-auto text-sm text-cream">{JSON.stringify(report?.reports?.report, null, 2)}</pre></div>}</div>; }
export function FinanceForecasting() { const [data, setData] = useState<any>(); const [error, setError] = useState(''); useEffect(() => { financeApi.getForecasting().then((response: any) => setData(response.forecasting)).catch((err: any) => setError(err.message)); }, []); return <div className="space-y-6 max-w-5xl"><h2 className="font-heading text-2xl font-bold text-cream">Forecasting</h2>{error ? <p className="text-rose-300">{error}</p> : !data ? <p className="text-ink/50">Loading historical revenue…</p> : !data.sufficientData ? <EmptyState title="Insufficient historical data" description="At least three months of completed Home Services revenue are required for a calculated estimate." /> : <div className="rounded-2xl border border-white/10 bg-navy-800/50 p-6"><p className="text-ink/60">Method: {data.method}. Estimates are calculations, not actual revenue.</p><DataTable data={data.estimates} keyExtractor={(row: any) => String(row.monthsAhead)} columns={[{ header: 'Months ahead', render: (row: any) => row.monthsAhead }, { header: 'Calculated estimate', render: (row: any) => currency(row.estimatedRevenue) }]} /></div>}</div>; }
export function UnsupportedFinanceFeature({ title }: { title: string }) { return <div className="max-w-3xl"><EmptyState title={`${title} is not available yet`} description="Luxora does not yet have an approved source-of-truth for this Finance feature, so no records or figures are shown." /></div>; }
