import { useState } from 'react';
import { MousePointerClick, Users, Timer, Activity, TrendingUp, BarChart3, LineChart, Target, Brain, ArrowUpRight, ArrowDownRight } from 'lucide-react';
import { DashboardHeader } from '../../../components/dashboard/shared/headers/DashboardHeader';
import { KPICard } from '../../../components/dashboard/shared/cards/KPICard';
import { GoldButton } from '../../../components/ui/ui';
import { ActivityTimeline } from '../../../components/dashboard/shared/timelines/ActivityTimeline';

export default function Analytics() {
  const [activeTimeframe, setActiveTimeframe] = useState('Last 30 Days');

  const insights = [
    { title: 'Platform Growth Target', desc: 'On track to hit 150K active users by end of Q4.', time: 'Generated by AI', icon: TrendingUp, color: 'text-emerald-400' },
    { title: 'Conversion Funnel Alert', desc: 'Drop-off rate at Step 3 increased by 4% this week.', time: 'Requires Attention', icon: Target, color: 'text-orange-400' },
    { title: 'Feature Adoption', desc: 'New Mortgage Calculator usage exceeded expectations by 210%.', time: 'Success Metric', icon: Activity, color: 'text-blue-400' }
  ];

  return (
    <div className="space-y-6 pb-12">
      <DashboardHeader 
        name="Executive Analytics & Forecasting" 
        subtitle="Platform growth forecast, business intelligence, and cross-department KPIs."
        actions={
          <div className="flex gap-3">
            <select 
              value={activeTimeframe}
              onChange={(e) => setActiveTimeframe(e.target.value)}
              className="bg-navy-900/50 border border-white/10 text-sm text-cream rounded-lg px-3 py-2 appearance-none focus:outline-none focus:border-gold-400"
            >
              <option>Last 30 Days</option>
              <option>Last 90 Days</option>
              <option>Year to Date</option>
            </select>
            <GoldButton className="flex items-center gap-2">
              <Brain className="h-4 w-4" /> Run Forecast
            </GoldButton>
          </div>
        }
      />

      <div className="grid md:grid-cols-3 gap-6">
        {/* Executive KPI Wall / Cross-Department Summary */}
        <div className="md:col-span-2 bg-gradient-to-br from-navy-800 to-navy-900 border border-white/10 rounded-2xl p-6 flex flex-col justify-center">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-2 bg-purple-400/20 rounded-xl">
              <BarChart3 className="h-6 w-6 text-purple-400" />
            </div>
            <h3 className="font-heading text-xl font-bold text-cream">Cross-Department Performance Summary</h3>
          </div>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
            <div className="bg-navy-900/50 p-4 rounded-xl border border-white/5">
               <div className="text-sm text-ink/60 mb-1 flex items-center gap-2"><MousePointerClick className="h-4 w-4" /> CTR</div>
               <div className="text-2xl font-bold text-cream">8.4%</div>
               <div className="text-xs text-emerald-400 mt-1 flex items-center gap-1"><ArrowUpRight className="h-3 w-3" /> +4.2%</div>
            </div>
            <div className="bg-navy-900/50 p-4 rounded-xl border border-white/5">
               <div className="text-sm text-ink/60 mb-1 flex items-center gap-2"><Users className="h-4 w-4" /> Retention</div>
               <div className="text-2xl font-bold text-cream">64.2%</div>
               <div className="text-xs text-emerald-400 mt-1 flex items-center gap-1"><ArrowUpRight className="h-3 w-3" /> +12.1%</div>
            </div>
            <div className="bg-navy-900/50 p-4 rounded-xl border border-white/5">
               <div className="text-sm text-ink/60 mb-1 flex items-center gap-2"><Timer className="h-4 w-4" /> Avg Session</div>
               <div className="text-2xl font-bold text-cream">4m 12s</div>
               <div className="text-xs text-rose-400 mt-1 flex items-center gap-1"><ArrowDownRight className="h-3 w-3" /> -2.4%</div>
            </div>
            <div className="bg-navy-900/50 p-4 rounded-xl border border-white/5">
               <div className="text-sm text-ink/60 mb-1 flex items-center gap-2"><Target className="h-4 w-4" /> Conversion</div>
               <div className="text-2xl font-bold text-cream">3.2%</div>
               <div className="text-xs text-emerald-400 mt-1 flex items-center gap-1"><ArrowUpRight className="h-3 w-3" /> +0.5%</div>
            </div>
          </div>
          
          <div className="space-y-4 max-w-2xl mx-auto w-full mt-4">
             <div className="text-sm font-medium text-cream mb-2 text-center">User Conversion Funnel</div>
             <div className="relative">
                <div className="bg-navy-900/80 border border-white/10 rounded-xl p-3 flex justify-between items-center relative z-10 w-full text-sm">
                  <span className="text-cream">1. Landing Page Visitors</span>
                  <span className="font-bold text-blue-400">142,500</span>
                </div>
                <div className="absolute left-1/2 -bottom-3 w-px h-3 bg-white/20"></div>
             </div>
             <div className="relative flex justify-center">
                <div className="bg-navy-900/80 border border-white/10 rounded-xl p-3 flex justify-between items-center relative z-10 w-11/12 text-sm">
                  <span className="text-cream">2. Searched for Property</span>
                  <span className="font-bold text-blue-400">89,200</span>
                </div>
                <div className="absolute left-1/2 -bottom-3 w-px h-3 bg-white/20"></div>
             </div>
             <div className="relative flex justify-center">
                <div className="bg-navy-900/80 border border-white/10 rounded-xl p-3 flex justify-between items-center relative z-10 w-5/6 text-sm">
                  <span className="text-cream">3. Registered / Logged In</span>
                  <span className="font-bold text-blue-400">45,100</span>
                </div>
                <div className="absolute left-1/2 -bottom-3 w-px h-3 bg-white/20"></div>
             </div>
             <div className="relative flex justify-center">
                <div className="bg-gold-400/10 border border-gold-400/30 rounded-xl p-3 flex justify-between items-center relative z-10 w-3/4 text-sm">
                  <span className="font-semibold text-gold-400">4. Contacted Agent</span>
                  <span className="font-bold text-gold-400">12,450</span>
                </div>
             </div>
          </div>
        </div>

        {/* Executive Insights Feed */}
        <div className="space-y-6">
          <ActivityTimeline title="Executive AI Insights Feed" items={insights} />
        </div>
      </div>

      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
        <KPICard title="Customer Acquisition Cost" value="₦4,500" trend="-5% vs Last Q" trendColor="text-emerald-400" icon={Activity} />
        <KPICard title="Lifetime Value (LTV)" value="₦185K" trend="+12% vs Last Q" trendColor="text-emerald-400" icon={TrendingUp} />
        <KPICard title="Platform Viral Coefficient" value="1.2" trend="Highly Viral" trendColor="text-emerald-400" icon={Users} />
        <KPICard title="Core Action Rate" value="48%" trend="Engaged Users" trendColor="text-blue-400" icon={MousePointerClick} />
      </div>

      <div className="grid lg:grid-cols-2 gap-6">
        {/* Business Forecast Engine */}
        <div className="rounded-2xl border border-white/10 bg-navy-800/50 p-6 flex flex-col justify-center items-center min-h-[300px]">
          <LineChart className="h-16 w-16 text-emerald-400/50 mb-4" />
          <h3 className="font-heading text-xl font-bold text-cream">Strategic Forecast Dashboard</h3>
          <p className="text-sm text-ink/60 mt-2 text-center max-w-sm">
            Interactive predictive models for platform growth, revenue trajectories, and market penetration would render here.
          </p>
        </div>

        <div className="rounded-2xl border border-white/10 bg-navy-800/50 p-6 flex flex-col justify-center items-center min-h-[300px]">
          <BarChart3 className="h-16 w-16 text-blue-400/50 mb-4" />
          <h3 className="font-heading text-xl font-bold text-cream">National Growth Indicators</h3>
          <p className="text-sm text-ink/60 mt-2 text-center max-w-sm">
            Comprehensive bar charts displaying user acquisition by region, marketing channel attribution, and cohort retention.
          </p>
        </div>
      </div>
    </div>
  );
}
