import { useCallback, useEffect, useState } from 'react';
import { Activity, Building2, Crown, FileCheck, RefreshCw, ShieldAlert, Users, Wrench } from 'lucide-react';
import { DashboardHeader } from '../../../components/dashboard/shared/headers/DashboardHeader';
import { KPICard } from '../../../components/dashboard/shared/cards/KPICard';
import { GhostButton } from '../../../components/ui/ui';
import { superAdminApi } from '../../../api/super-admin.api';
type Lifecycle = { _id?: string | null; count?: number };
const display = (value?: number) => value === undefined ? '—' : value.toLocaleString();
const get = (data: any, group: string, field: string) => data?.[group]?.[field] as number | undefined;
const total = (items: Lifecycle[] | undefined) => Array.isArray(items) ? items.reduce((sum, item) => sum + (item.count || 0), 0) : undefined;
const statuses = (items: Lifecycle[] | undefined) => Array.isArray(items) && items.length ? items.map((item) => `${item._id || 'Unspecified'}: ${item.count || 0}`).join(' · ') : 'No lifecycle records';
export default function Overview() {
  const [overview, setOverview] = useState<any>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response: any = await superAdminApi.getOverview(); setOverview(response?.overview ?? response?.data?.overview ?? response); } catch (error: any) { setOverview(null); setError(error?.message || 'Unable to load the platform overview.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const cards = [['Total Properties', 'platform', 'totalProperties', Building2], ['Published Properties', 'platform', 'publishedProperties', FileCheck], ['Active Users', 'platform', 'activeUsers', Users], ['Active Agencies', 'platform', 'activeAgencies', Building2], ['Active Agents', 'platform', 'activeAgents', Users], ['Paid Payment Records', 'finance', 'paidPayments', Activity], ['Active Internal Staff', 'workforce', 'activeInternalStaff', Users], ['Open Complaints', 'oversight', 'openComplaints', ShieldAlert], ['Pending Verifications', 'oversight', 'pendingVerifications', FileCheck], ['Audit Events', 'oversight', 'auditEvents', Activity], ['Procurement Records', 'operations', 'procurementRecords', Wrench], ['Home Service Transactions', 'operations', 'homeServiceTransactions', Wrench]] as const;
  const paid = overview?.finance?.paidPayments; const commissions = overview?.finance?.commissionLifecycle as Lifecycle[] | undefined; const mortgages = overview?.finance?.mortgagePipeline as Lifecycle[] | undefined;
  return <div className="space-y-6 pb-12"><DashboardHeader name="Platform Command Center" subtitle="Verified global platform operations." actions={<GhostButton onClick={() => void load()}><RefreshCw className="mr-2 inline h-4 w-4" />Refresh</GhostButton>} />{error && <p className="rounded-xl border border-rose-400/30 bg-rose-400/10 p-4 text-rose-200">{error} <button onClick={() => void load()} className="underline">Retry</button></p>}<div className="rounded-2xl border border-gold-400/20 bg-gold-400/5 p-6"><h3 className="flex gap-2 font-heading text-lg font-bold text-cream"><Crown className="h-5 w-5 text-gold-400" />Executive Summary</h3><p className="mt-2 text-sm text-ink/80">Counts are recorded platform totals. Paid payments are actual amounts; commission and mortgage figures are lifecycle counts.</p></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([title, group, field, icon]) => <KPICard key={field} title={title} value={loading ? 'Loading…' : field === 'paidPayments' ? display(paid?.count) : display(get(overview, group, field))} trend={loading ? 'Loading verified data' : field === 'paidPayments' ? 'Actual recorded paid payments' : group} trendColor="text-ink/60" icon={icon} />)}</div><section className="rounded-2xl border border-white/10 bg-navy-800/50 p-6"><h3 className="font-heading text-lg font-bold text-cream">Finance lifecycle</h3><div className="mt-4 grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-ink/60">Actual paid amount</p><p className="text-2xl font-bold text-cream">{loading ? '…' : paid?.amount === undefined ? '—' : `₦${Number(paid.amount).toLocaleString()}`}</p></div><div><p className="text-xs text-ink/60">Commission lifecycle count</p><p className="text-2xl font-bold text-cream">{loading ? '…' : display(total(commissions))}</p><p className="mt-1 text-xs text-ink/60">{loading ? '' : statuses(commissions)}</p></div><div><p className="text-xs text-ink/60">Mortgage pipeline count</p><p className="text-2xl font-bold text-cream">{loading ? '…' : display(total(mortgages))}</p><p className="mt-1 text-xs text-ink/60">{loading ? '' : statuses(mortgages)}</p></div></div></section><section className="rounded-2xl border border-white/10 bg-navy-800/50 p-6"><h3 className="font-heading text-lg font-bold text-cream">Platform health</h3><p className="mt-2 text-sm text-ink/60">Health scores, uptime, service status, and assignment metrics are unavailable from the verified endpoint and are intentionally not estimated.</p></section></div>;
}
