import { FileBarChart, Download, Clock, Lightbulb, Activity, CheckCircle2, Search, Filter } from 'lucide-react';
import { DashboardHeader } from '../../../components/dashboard/shared/headers/DashboardHeader';
import { KPICard } from '../../../components/dashboard/shared/cards/KPICard';
import { ActivityTimeline } from '../../../components/dashboard/shared/timelines/ActivityTimeline';
import { GhostButton, GoldButton } from '../../../components/ui/ui';

export default function Reports() {

  const generatedReports = [
    { title: 'Q3 Executive Board Meeting Pack', desc: 'Generated by AI Assistant', time: 'Today, 8:00 AM', icon: CheckCircle2, color: 'text-emerald-400' },
    { title: 'Monthly Revenue Forecast', desc: 'Automated Schedule', time: 'Yesterday', icon: Clock, color: 'text-blue-400' },
    { title: 'Compliance Audit Report', desc: 'Requested by Legal Dept', time: 'Oct 15', icon: FileBarChart, color: 'text-gold-400' }
  ];

  const recommendations = [
    { text: 'Consider generating a "Q4 User Growth Projection" based on recent signup spikes.', icon: Lightbulb, color: 'text-gold-400' },
    { text: 'Your "Weekly Agency Performance" report is ready for review.', icon: Activity, color: 'text-blue-400' }
  ];

  return (
    <div className="space-y-6 pb-12">
      <DashboardHeader 
        name="Executive Reporting Center" 
        subtitle="Intelligent report generation, scheduled exports, and board-ready meeting packs."
        actions={
          <div className="flex gap-3">
            <GhostButton className="flex items-center gap-2">
              <Clock className="h-4 w-4" /> Scheduled
            </GhostButton>
            <GoldButton className="flex items-center gap-2">
              <FileBarChart className="h-4 w-4" /> Generate Report
            </GoldButton>
          </div>
        }
      />

      <div className="grid md:grid-cols-3 gap-6">
        <div className="md:col-span-2 bg-gradient-to-br from-navy-800 to-navy-900 border border-white/10 rounded-2xl p-6 flex flex-col justify-center">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-2 bg-blue-400/20 rounded-xl">
              <FileBarChart className="h-6 w-6 text-blue-400" />
            </div>
            <h3 className="font-heading text-xl font-bold text-cream">Executive Board Meeting Pack</h3>
          </div>
          <div className="flex flex-col sm:flex-row gap-6 items-center">
            <div className="flex-1 space-y-4">
              <p className="text-sm text-ink/80 leading-relaxed">
                The comprehensive Q3 2026 Executive Board Pack is ready. It includes complete financial analytics, user growth projections, compliance scores, and executive summaries.
              </p>
              <div className="flex gap-3">
                <GoldButton className="flex items-center gap-2 text-xs">
                  <Download className="h-4 w-4" /> Download PDF Pack (14MB)
                </GoldButton>
                <GhostButton className="text-xs">View Online</GhostButton>
              </div>
            </div>
            <div className="w-full sm:w-1/3 bg-navy-900/50 p-4 rounded-xl border border-white/5 text-center">
              <div className="text-sm text-ink/60 mb-1">Version History</div>
              <div className="font-bold text-cream">v2.4 (Final)</div>
              <div className="text-xs text-emerald-400 mt-1">Approved for distribution</div>
            </div>
          </div>
        </div>

        <div className="rounded-2xl border border-white/10 bg-navy-800/50 p-6 flex flex-col">
          <h3 className="font-heading text-base font-bold text-cream mb-4 flex items-center gap-2">
            <Lightbulb className="h-4 w-4 text-gold-400" /> Intelligent Recommendations
          </h3>
          <div className="space-y-4 flex-1">
            {recommendations.map((rec, idx) => (
              <div key={idx} className="flex gap-3 bg-white/[0.02] border border-white/5 p-4 rounded-xl">
                <div className="pt-0.5"><rec.icon className={`h-4 w-4 ${rec.color}`} /></div>
                <div className="text-sm text-cream/90 leading-relaxed">{rec.text}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
        <KPICard title="Total Reports Generated" value="1,240" trend="YTD" trendColor="text-emerald-400" icon={FileBarChart} />
        <KPICard title="Scheduled Reports" value="24" trend="Active Weekly/Monthly" trendColor="text-blue-400" icon={Clock} />
        <KPICard title="Top Export Format" value="PDF" trend="68% of all exports" trendColor="text-gold-400" icon={Download} />
        <KPICard title="Generation Speed" value="1.2s" trend="Avg time" trendColor="text-emerald-400" icon={Activity} />
      </div>

      <div className="grid lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <div className="rounded-2xl border border-white/10 bg-navy-800/50 overflow-hidden flex flex-col h-full">
            <div className="p-6 border-b border-white/10 flex flex-col sm:flex-row justify-between gap-4 sm:items-center">
              <h3 className="font-heading text-lg font-semibold text-cream">Frequently Viewed Reports</h3>
              <div className="flex gap-2">
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-ink/40" />
                  <input type="text" placeholder="Search reports..." className="h-9 w-full sm:w-64 rounded-lg border border-white/10 bg-navy-900/50 pl-10 pr-4 text-sm text-cream focus:border-gold-400 focus:outline-none focus:ring-1 focus:ring-gold-400" />
                </div>
                <GhostButton className="h-9 w-9 p-0 flex items-center justify-center shrink-0"><Filter className="h-4 w-4" /></GhostButton>
              </div>
            </div>
            
            <div className="p-6 grid sm:grid-cols-2 gap-4">
              <div className="p-4 bg-navy-900/50 border border-white/5 rounded-xl hover:bg-white/[0.02] transition-colors cursor-pointer group">
                <h4 className="font-semibold text-cream mb-1 flex items-center gap-2"><FileBarChart className="h-4 w-4 text-gold-400" /> Quarterly Financial Review</h4>
                <p className="text-xs text-ink/60 mb-4 line-clamp-2">Comprehensive breakdown of revenue, GMV, OPEX, and profitability margins across all operating regions.</p>
                <div className="flex justify-between items-center text-xs">
                  <span className="text-ink/40">Viewed 142 times</span>
                  <span className="text-gold-400 opacity-0 group-hover:opacity-100 transition-opacity">Download PDF</span>
                </div>
              </div>
              <div className="p-4 bg-navy-900/50 border border-white/5 rounded-xl hover:bg-white/[0.02] transition-colors cursor-pointer group">
                <h4 className="font-semibold text-cream mb-1 flex items-center gap-2"><FileBarChart className="h-4 w-4 text-blue-400" /> Investor Relations Deck</h4>
                <p className="text-xs text-ink/60 mb-4 line-clamp-2">Platform growth metrics, active listings, user acquisition cost, and strategic expansion plans.</p>
                <div className="flex justify-between items-center text-xs">
                  <span className="text-ink/40">Viewed 89 times</span>
                  <span className="text-blue-400 opacity-0 group-hover:opacity-100 transition-opacity">Download PDF</span>
                </div>
              </div>
              <div className="p-4 bg-navy-900/50 border border-white/5 rounded-xl hover:bg-white/[0.02] transition-colors cursor-pointer group">
                <h4 className="font-semibold text-cream mb-1 flex items-center gap-2"><FileBarChart className="h-4 w-4 text-emerald-400" /> Agency Performance Matrix</h4>
                <p className="text-xs text-ink/60 mb-4 line-clamp-2">Top performing agencies by revenue contribution, regional dominance, and compliance adherence.</p>
                <div className="flex justify-between items-center text-xs">
                  <span className="text-ink/40">Viewed 215 times</span>
                  <span className="text-emerald-400 opacity-0 group-hover:opacity-100 transition-opacity">Download CSV</span>
                </div>
              </div>
              <div className="p-4 bg-navy-900/50 border border-white/5 rounded-xl hover:bg-white/[0.02] transition-colors cursor-pointer group">
                <h4 className="font-semibold text-cream mb-1 flex items-center gap-2"><FileBarChart className="h-4 w-4 text-purple-400" /> Enterprise Risk Summary</h4>
                <p className="text-xs text-ink/60 mb-4 line-clamp-2">Aggregated compliance scores, fraud detection metrics, and internal audit statuses.</p>
                <div className="flex justify-between items-center text-xs">
                  <span className="text-ink/40">Viewed 64 times</span>
                  <span className="text-purple-400 opacity-0 group-hover:opacity-100 transition-opacity">Download PDF</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="space-y-6">
          <ActivityTimeline title="Report Generation & Export History" items={generatedReports} />
        </div>
      </div>
    </div>
  );
}
