import { useCallback, useEffect, useState } from 'react';
import { RefreshCw } from 'lucide-react';
import { DashboardHeader } from '../../../components/dashboard/shared/headers/DashboardHeader';
import { GhostButton } from '../../../components/ui/ui';
import { superAdminApi } from '../../../api/super-admin.api';
type Lifecycle = { _id?: string | null; count?: number };
const total = (items: Lifecycle[] | undefined) => Array.isArray(items) ? items.reduce((sum, item) => sum + (item.count || 0), 0) : undefined;
const LifecycleCounts = ({ title, items }: { title: string; items: Lifecycle[] | undefined }) => <section className="rounded-2xl border border-white/10 bg-navy-800/50 p-6"><h3 className="font-heading text-lg font-bold text-cream">{title}</h3><p className="mt-1 text-sm text-ink/60">Lifecycle count: {total(items) === undefined ? '—' : total(items)?.toLocaleString()}</p>{Array.isArray(items) && items.length ? <div className="mt-4 space-y-2">{items.map((item, index) => <div key={`${item._id}-${index}`} className="flex justify-between text-sm"><span className="text-ink/70">{item._id || 'Unspecified'}</span><span className="font-semibold text-cream">{item.count ?? 0}</span></div>)}</div> : <p className="mt-4 text-sm text-ink/60">No lifecycle records.</p>}</section>;
export default function Revenue() { const [data, setData] = useState<any>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const load = useCallback(async () => { setLoading(true); setError(null); try { const r: any = await superAdminApi.getOverview(); setData(r?.overview ?? r?.data?.overview ?? r); } catch (e: any) { setData(null); setError(e?.message || 'Unable to load revenue data.'); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]); const paid = data?.finance?.paidPayments; return <div className="space-y-6 pb-12"><DashboardHeader name="Revenue" subtitle="Verified payment records and financial lifecycle counts." actions={<GhostButton onClick={() => void load()}><RefreshCw className="mr-2 inline h-4 w-4" />Refresh</GhostButton>} />{error && <p className="rounded-xl border border-rose-400/30 bg-rose-400/10 p-4 text-rose-200">{error} <button className="underline" onClick={() => void load()}>Retry</button></p>}{loading ? <p className="rounded-2xl border border-white/10 p-8 text-ink/60">Loading verified revenue data…</p> : <><section className="rounded-2xl border border-gold-400/20 bg-gold-400/5 p-6"><p className="text-sm text-ink/60">Actual recorded paid payments</p><p className="mt-2 text-3xl font-bold text-cream">{paid?.amount === undefined ? '—' : `₦${Number(paid.amount).toLocaleString()}`}</p><p className="mt-1 text-sm text-ink/60">{paid?.count === undefined ? '—' : paid.count.toLocaleString()} paid payment records</p></section><div className="grid gap-6 lg:grid-cols-2"><LifecycleCounts title="Commission lifecycle" items={data?.finance?.commissionLifecycle} /><LifecycleCounts title="Mortgage pipeline" items={data?.finance?.mortgagePipeline} /></div></>}</div>; }
