import { useCallback } from 'react';
import { GhostButton } from '../../../components/ui/ui';
import { KPICard } from '../../../components/dashboard/shared/cards/KPICard';
import { Building2, TrendingDown, TrendingUp, Users } from 'lucide-react';
import { propertyManagementApi } from '../../../api/property-management.api';
import { usePropertyManagementResource } from '../usePropertyManagementResource';
const money = (n: number) => `₦${Number(n || 0).toLocaleString()}`;
export default function Analytics() { const load = useCallback(async () => (await propertyManagementApi.analytics() as any).analytics, []); const { data, loading, error, refresh } = usePropertyManagementResource<any>(load, [load]); if (loading) return <div className="h-80 animate-pulse rounded-2xl bg-white/10" />; if (error) return <div className="text-rose-200">{error} <GhostButton onClick={() => void refresh()}>Retry</GhostButton></div>; const a = data!; return <div className="space-y-6 max-w-7xl"><div><h2 className="font-heading text-2xl font-bold text-cream">Portfolio Analytics</h2><p className="text-sm text-ink/60">Metrics reported by the Property Manager API.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><KPICard title="Properties" value={String(a.propertyCount)} icon={Building2} iconColor="text-gold-400" /><KPICard title="Active Occupancies" value={String(a.activeOccupancies)} icon={Users} iconColor="text-emerald-400" /><KPICard title="Rent Collected" value={money(a.rentCollected)} icon={TrendingUp} iconColor="text-emerald-400" /><KPICard title="Overdue Rent" value={money(a.overdueRent)} icon={TrendingDown} iconColor="text-rose-400" /></div><div className="rounded-2xl border border-white/10 bg-navy-800/50 p-6"><h3 className="font-heading text-lg font-semibold text-cream">Operating Position</h3><dl className="mt-5 grid gap-4 sm:grid-cols-2 text-sm"><Stat label="Approved expenses" value={money(a.approvedExpenses)} /><Stat label="Non-rent income" value={money(a.nonRentIncome)} /><Stat label="Net operating amount" value={money(a.netOperatingAmount)} /><Stat label="Occupancy records" value={String(a.totalOccupancyRecords)} /></dl>{!a.sufficientData && <p className="mt-5 text-ink/60">There is not enough portfolio data for further analysis.</p>}<p className="mt-5 text-xs text-ink/50">Historical chart series are unavailable from the current API and are intentionally not estimated.</p></div></div>; }
function Stat({ label, value }: { label: string; value: string }) { return <div><dt className="text-ink/60">{label}</dt><dd className="mt-1 font-semibold text-cream">{value}</dd></div>; }
