import { useCallback, useState } from 'react';
import { Eye } from 'lucide-react';
import { DataTable } from '../../../components/dashboard/shared/tables/DataTable';
import { EnterpriseStatusBadge } from '../../../components/enterprise/EnterpriseStatusBadge';
import { EnterpriseDetailDrawer } from '../../../components/enterprise/EnterpriseDetailDrawer';
import { GhostButton } from '../../../components/ui/ui';
import { propertyManagementApi } from '../../../api/property-management.api';
import { usePropertyManagementResource } from '../usePropertyManagementResource';
const date = (value?: string) => value ? new Date(value).toLocaleDateString() : '—';
export default function Inspections() { const load = useCallback(async () => (await propertyManagementApi.list('inspections') as any).inspections || [], []); const { data, loading, error, refresh } = usePropertyManagementResource<any[]>(load, [load]); const [selected, setSelected] = useState<any>(null); if (loading) return <div className="h-80 animate-pulse rounded-2xl bg-white/10" />; if (error) return <div className="text-rose-200">{error} <GhostButton onClick={() => void refresh()}>Retry</GhostButton></div>; return <div className="space-y-6 max-w-5xl"><div><h2 className="font-heading text-2xl font-bold text-cream">Property Inspections</h2><p className="text-sm text-ink/60">Inspection history from your portfolio.</p></div><DataTable data={data!} keyExtractor={inspection => inspection._id} emptyState={<p className="text-center text-ink/60">No inspections have been scheduled.</p>} columns={[{ header: 'Property', render: inspection => <span className="font-semibold text-cream"><Eye className="mr-2 inline h-4 w-4" />{inspection.property?.title || '—'}</span> }, { header: 'Type', render: inspection => inspection.type }, { header: 'Scheduled', render: inspection => date(inspection.scheduledAt) }, { header: 'Inspector', render: inspection => inspection.inspectorName || inspection.inspector?.fullName || '—' }, { header: 'Status', render: inspection => <EnterpriseStatusBadge status={inspection.status} /> }, { header: 'Score', render: inspection => inspection.score ?? '—' }]} onRowClick={setSelected} /><EnterpriseDetailDrawer isOpen={!!selected} onClose={() => setSelected(null)} title="Inspection Details">{selected && <div className="space-y-3"><p>Unit: {selected.unit || '—'}</p><p>Findings: {selected.findings?.length ? selected.findings.join(', ') : 'No findings recorded.'}</p>{selected.reportUrl ? <a className="text-gold-400" href={selected.reportUrl} target="_blank" rel="noreferrer">View report</a> : <p className="text-ink/60">No report reference available.</p>}<GhostButton disabled title="Property Manager document uploads are not supported">Upload Report</GhostButton></div>}</EnterpriseDetailDrawer></div>; }
