import { useCallback, useState } from 'react';
import { FileText } from 'lucide-react';
import { DataTable } from '../../../components/dashboard/shared/tables/DataTable';
import { EnterpriseStatusBadge } from '../../../components/enterprise/EnterpriseStatusBadge';
import { EnterpriseDetailDrawer } from '../../../components/enterprise/EnterpriseDetailDrawer';
import { GhostButton } from '../../../components/ui/ui';
import { propertyManagementApi } from '../../../api/property-management.api';
import { usePropertyManagementResource } from '../usePropertyManagementResource';
const date = (value?: string) => value ? new Date(value).toLocaleDateString() : '—';
export default function LeaseTracking() { const load = useCallback(async () => (await propertyManagementApi.list('leases') as any).leases || [], []); const { data, loading, error, refresh } = usePropertyManagementResource<any[]>(load, [load]); const [selected, setSelected] = useState<any>(null); if (loading) return <div className="h-80 animate-pulse rounded-2xl bg-white/10" />; if (error) return <div className="text-rose-200">{error} <GhostButton onClick={() => void refresh()}>Retry</GhostButton></div>; return <div className="space-y-6 max-w-5xl"><div><h2 className="font-heading text-2xl font-bold text-cream">Lease Renewals & Tracking</h2><p className="text-sm text-ink/60">Current lease records and lifecycle status.</p></div><DataTable data={data!} keyExtractor={lease => lease._id} emptyState={<p className="text-center text-ink/60">No leases have been created.</p>} columns={[{ header: 'Tenant', render: lease => <span className="font-semibold text-cream"><FileText className="mr-2 inline h-4 w-4" />{lease.tenant?.fullName || '—'}</span> }, { header: 'Property', render: lease => lease.property?.title || '—' }, { header: 'Start', render: lease => date(lease.startDate) }, { header: 'End', render: lease => date(lease.endDate) }, { header: 'Status', render: lease => <EnterpriseStatusBadge status={lease.status} /> }]} onRowClick={setSelected} /><EnterpriseDetailDrawer isOpen={!!selected} onClose={() => setSelected(null)} title="Lease Details">{selected && <div className="space-y-3"><p>Unit: {selected.unit || '—'}</p><p>Monthly rent: ₦{Number(selected.monthlyRent || 0).toLocaleString()}</p><p>Deposit: ₦{Number(selected.deposit || 0).toLocaleString()}</p><p className="text-ink/60">Renewal and termination require new term dates/reason. Use the lease action form when it is available.</p></div>}</EnterpriseDetailDrawer></div>; }
