import { useCallback, useState } from 'react';
import { Plus, Wrench } from 'lucide-react';
import { GoldButton, GhostButton } from '../../../components/ui/ui';
import { DataTable } from '../../../components/dashboard/shared/tables/DataTable';
import { EnterpriseStatusBadge } from '../../../components/enterprise/EnterpriseStatusBadge';
import { EnterpriseDetailDrawer } from '../../../components/enterprise/EnterpriseDetailDrawer';
import { MaintenanceRequestModal } from './modals/MaintenanceRequestModal';
import { propertyManagementApi, notifyPropertyManagementDataChanged } from '../../../api/property-management.api';
import { usePropertyManagementResource } from '../usePropertyManagementResource';
export default function Maintenance() { const load = useCallback(async () => { const [workOrderResult, propertyResult] = await Promise.all([propertyManagementApi.list('work-orders'), propertyManagementApi.properties()]); return { workOrders: (workOrderResult as any).workOrders || [], properties: (propertyResult as any).properties || [] }; }, []); const { data, loading, error, refresh } = usePropertyManagementResource(load, [load]); const [selected, setSelected] = useState<any>(null); const [creating, setCreating] = useState(false); const [saving, setSaving] = useState(false); const [mutationError, setMutationError] = useState<string | null>(null); const create = async (values: any) => { setSaving(true); setMutationError(null); try { await propertyManagementApi.create('work-orders', values); notifyPropertyManagementDataChanged(); setCreating(false); await refresh(); } catch (err: any) { setMutationError(err?.message || 'Unable to create work order.'); } finally { setSaving(false); } }; if (loading) return <div className="h-80 animate-pulse rounded-2xl bg-white/10" />; if (error) return <div className="text-rose-200">{error} <GhostButton onClick={() => void refresh()}>Retry</GhostButton></div>; return <div className="space-y-6 max-w-5xl"><div className="flex justify-between"><div><h2 className="font-heading text-2xl font-bold text-cream">Maintenance</h2><p className="text-sm text-ink/60">Portfolio work orders.</p></div><GoldButton onClick={() => setCreating(true)}><Plus className="mr-2 inline h-4 w-4" />Create Ticket</GoldButton></div>{mutationError && <p className="text-rose-300">{mutationError}</p>}<DataTable data={data!.workOrders} keyExtractor={w => w._id} emptyState={<p className="text-center text-ink/60">No work orders have been created.</p>} columns={[{ header: 'Issue', render: w => <span className="font-semibold text-cream"><Wrench className="mr-2 inline h-4 w-4" />{w.title}</span> }, { header: 'Property', render: w => w.property?.title || '—' }, { header: 'Tenant', render: w => w.tenant?.fullName || '—' }, { header: 'Priority', render: w => <EnterpriseStatusBadge status={w.priority} /> }, { header: 'Status', render: w => <EnterpriseStatusBadge status={w.status} /> }]} onRowClick={setSelected} /><EnterpriseDetailDrawer isOpen={!!selected} onClose={() => setSelected(null)} title="Maintenance Details">{selected && <div className="space-y-3"><p className="text-cream">{selected.description || 'No description supplied.'}</p><p>Estimated cost: {selected.estimatedCost == null ? '—' : `₦${Number(selected.estimatedCost).toLocaleString()}`}</p><GhostButton disabled title="Assignment and status changes require a supported vendor/assignee selection">Assign / Update Status</GhostButton></div>}</EnterpriseDetailDrawer><MaintenanceRequestModal isOpen={creating} onClose={() => !saving && setCreating(false)} properties={data!.properties} submitting={saving} error={mutationError} onSubmit={create} /></div>; }
