import { useEffect, useRef, useState } from 'react';
import { Camera, KeyRound, Mail, Smartphone, User } from 'lucide-react';
import PasswordChangeModal from '../../BuyerDashboard/components/modals/PasswordChangeModal';
import { GoldButton, GhostButton } from '../../../components/ui/ui';
import { SettingsLayout } from '../../../components/dashboard/shared/layouts/SettingsLayout';
import { SettingsSection } from '../../../components/dashboard/shared/settings/SettingsSection';
import { useSession } from '../../../contexts/SessionContext';

export default function Settings() {
  const { user, updateAccountSettings, updateProfilePhoto, changePassword } = useSession();
  const [fullName, setFullName] = useState(user?.name || ''); const [email, setEmail] = useState(user?.email || ''); const [phone, setPhone] = useState(user?.phone || ''); const [saving, setSaving] = useState(false); const [success, setSuccess] = useState(''); const [error, setError] = useState(''); const [passwordOpen, setPasswordOpen] = useState(false); const input = useRef<HTMLInputElement>(null);
  useEffect(() => { setFullName(user?.name || ''); setEmail(user?.email || ''); setPhone(user?.phone || ''); }, [user]);
  const save = async () => { setSaving(true); setError(''); setSuccess(''); try { await updateAccountSettings({ fullName, email, phone: phone.trim() || null }); setSuccess('Profile saved successfully.'); } catch (err: any) { setError(err?.message || 'Unable to save profile.'); } finally { setSaving(false); } };
  const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setError(''); try { await updateProfilePhoto(file); setSuccess('Profile picture updated successfully.'); } catch (err: any) { setError(err?.message || 'Unable to update profile picture.'); } finally { event.target.value = ''; } };
  const password = async (current: string, next: string) => { try { await changePassword(current, next); setPasswordOpen(false); setSuccess('Password changed successfully.'); } catch (err: any) { setError(err?.message || 'Unable to change password.'); } };
  const field = 'w-full rounded-xl border border-white/10 bg-navy-900/50 px-4 py-2.5 text-sm text-cream focus:border-gold-400/50 focus:outline-none';
  return <SettingsLayout title="Property Management Settings" subtitle="Manage your authenticated Luxora profile and security settings." saveSuccess={Boolean(success)} successMessage={success}><SettingsSection title="Profile Information" description="Changes are saved to your shared Luxora user account." headerAction={<GoldButton onClick={() => void save()} disabled={saving}>{saving ? 'Saving...' : 'Save Changes'}</GoldButton>}><div className="flex flex-col gap-8 md:flex-row"><div className="flex flex-col items-center gap-3"><button type="button" onClick={() => input.current?.click()} className="relative h-24 w-24 overflow-hidden rounded-full border-2 border-gold-400/20"><img src={user?.avatar || `https://ui-avatars.com/api/?name=${encodeURIComponent(user?.name || 'User')}&background=0D8ABC&color=fff`} alt="Profile" className="h-full w-full object-cover" /><Camera className="absolute inset-0 m-auto h-6 w-6 text-cream opacity-0 hover:opacity-100" /></button><GhostButton onClick={() => input.current?.click()}>Change Photo</GhostButton><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={upload} /></div><div className="grid flex-1 gap-5 md:grid-cols-2"><label className="text-xs text-ink/60"><span className="mb-2 flex gap-2"><User className="h-4 w-4" />Full Name</span><input className={field} value={fullName} onChange={(e) => setFullName(e.target.value)} /></label><label className="text-xs text-ink/60"><span className="mb-2 flex gap-2"><Mail className="h-4 w-4" />Email</span><input type="email" className={field} value={email} onChange={(e) => setEmail(e.target.value)} /></label><label className="text-xs text-ink/60"><span className="mb-2 flex gap-2"><Smartphone className="h-4 w-4" />Phone</span><input className={field} value={phone} onChange={(e) => setPhone(e.target.value)} /></label></div></div></SettingsSection>{error && <p className="rounded-xl border border-rose-400/25 bg-rose-400/10 p-3 text-sm text-rose-200">{error}</p>}<SettingsSection title="Security" description="Use your current password to set a new password."><div className="flex items-center justify-between rounded-xl border border-white/10 bg-navy-900/50 p-4"><span className="flex items-center gap-2 font-semibold text-cream"><KeyRound className="h-4 w-4 text-gold-400" />Password</span><GhostButton onClick={() => setPasswordOpen(true)}>Change Password</GhostButton></div></SettingsSection><PasswordChangeModal isOpen={passwordOpen} onClose={() => setPasswordOpen(false)} onSave={(current, next) => void password(current, next)} /></SettingsLayout>;
}
