import { useCallback, useState } from 'react';
import { Plus, Users } from 'lucide-react';
import { GoldButton, GhostButton } from '../../../components/ui/ui';
import { DataTable } from '../../../components/dashboard/shared/tables/DataTable';
import { DataTableToolbar } from '../../../components/dashboard/shared/filters/DataTableToolbar';
import { EnterpriseStatusBadge } from '../../../components/enterprise/EnterpriseStatusBadge';
import { EnterpriseDetailDrawer } from '../../../components/enterprise/EnterpriseDetailDrawer';
import { TenantFormModal } from './modals/TenantFormModal';
import { propertyManagementApi, notifyPropertyManagementDataChanged } from '../../../api/property-management.api';
import { usePropertyManagementResource } from '../usePropertyManagementResource';
interface Props { onNavigate?: (tab: string) => void }
export default function Tenants({ onNavigate }: Props) {
  const load = useCallback(async () => { const [tenantResult, propertyResult] = await Promise.all([propertyManagementApi.list('tenants'), propertyManagementApi.properties()]); return { tenants: (tenantResult as any).tenants || [], properties: (propertyResult as any).properties || [] }; }, []);
  const { data, loading, error, refresh } = usePropertyManagementResource(load, [load]); const [query, setQuery] = useState(''); const [selected, setSelected] = useState<any>(null); const [editing, setEditing] = useState<any | null>(null); const [saving, setSaving] = useState(false); const [mutationError, setMutationError] = useState<string | null>(null);
  const save = async (values: any) => { if (!data) return; setSaving(true); setMutationError(null); try { const payload = { fullName: values.fullName, email: values.email || null, phone: values.phone || null, unit: values.unit || null, status: values.status }; if (editing) await propertyManagementApi.update('tenants', editing._id, payload); else await propertyManagementApi.create('tenants', { ...payload, propertyId: values.propertyId || data.properties[0]?._id }); notifyPropertyManagementDataChanged(); setEditing(null); setSelected(null); await refresh(); } catch (err: any) { setMutationError(err?.message || 'Unable to save tenant.'); } finally { setSaving(false); } };
  if (loading) return <div className="h-80 animate-pulse rounded-2xl bg-white/10" />; if (error) return <div className="text-rose-200">{error} <GhostButton onClick={() => void refresh()}>Retry</GhostButton></div>; const tenants = data!.tenants.filter((t: any) => `${t.fullName} ${t.email || ''} ${t.phone || ''} ${t.property?.title || ''}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="space-y-6 max-w-5xl"><div className="flex items-center justify-between"><div><h2 className="font-heading text-2xl font-bold text-cream">Tenant Directory</h2><p className="text-sm text-ink/60">Occupancy records in your portfolio.</p></div><GoldButton onClick={() => setEditing({})}><Plus className="mr-2 h-4 w-4" />Add Tenant</GoldButton></div>{mutationError && <p className="text-sm text-rose-300">{mutationError}</p>}<DataTableToolbar searchValue={query} onSearchChange={setQuery} searchPlaceholder="Search tenants..." /><DataTable data={tenants} keyExtractor={t => t._id} emptyState={<p className="text-center text-ink/60">No tenants have been recorded.</p>} columns={[{ header: 'Tenant Name', render: t => <span className="font-semibold text-cream"><Users className="mr-2 inline h-4 w-4" />{t.fullName}</span> }, { header: 'Property & Unit', render: t => <>{t.property?.title || '—'} <span className="text-ink/50">{t.unit || ''}</span></> }, { header: 'Contact', render: t => t.phone || t.email || '—' }, { header: 'Status', render: t => <EnterpriseStatusBadge status={t.status} /> }]} onRowClick={setSelected} /><EnterpriseDetailDrawer isOpen={!!selected} onClose={() => setSelected(null)} title="Tenant Details">{selected && <div className="space-y-4"><p className="text-lg font-semibold text-cream">{selected.fullName}</p><p>Email: {selected.email || '—'}</p><p>Phone: {selected.phone || '—'}</p><p>Move in: {selected.moveInDate ? new Date(selected.moveInDate).toLocaleDateString() : '—'}</p><GoldButton onClick={() => setEditing(selected)}>Edit Profile</GoldButton><GhostButton onClick={() => onNavigate?.('Lease Tracking')}>Manage Lease</GhostButton></div>}</EnterpriseDetailDrawer><TenantFormModal isOpen={editing !== null} onClose={() => { if (!saving) setEditing(null); }} initialData={editing} properties={data!.properties} submitting={saving} error={mutationError} onSubmit={save} /></div>;
}
